<?php

namespace ContainerOn88Sev;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendMailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SendMail' shared autowired service.
     *
     * @return \App\Service\SendMail
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SendMail.php';

        return $container->privates['App\\Service\\SendMail'] = new \App\Service\SendMail();
    }
}
