<?php

namespace ContainerCW6aQjF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendMailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ed6AnDv.App\Service\SendMail' shared service.
     *
     * @return \App\Service\SendMail
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ed6AnDv": it references class "App\\Service\\SendMail" but no such service exists.');
    }
}
