<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOn88Sev\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOn88Sev/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOn88Sev.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOn88Sev\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOn88Sev\App_KernelDevDebugContainer([
    'container.build_hash' => 'On88Sev',
    'container.build_id' => 'df3eabbe',
    'container.build_time' => 1648431373,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOn88Sev');
